
abstract=Ontology covering the domain of the Kaggle dataset Pizza Restaurants and the Pizza They Sell: https://www.kaggle.com/datafiniti/pizza-restaurants-and-the-pizza-they-sell
ontologyTitle=Pizza-Restaurants ontology
ontologyPrefix=[Ontology NS Prefix]
ontologyNamespaceURI=https://w3id.org/city-kgs/restaurants
ontologyName=Pizza-Restaurants ontology
thisVersionURI=https://w3id.org/city-kgs/restaurants/1.0.0
latestVersionURI=
previousVersionURI=
dateCreated=
dateModified=
ontologyRevisionNumber=Version 02/03/2024
licenseURI=https://www.apache.org/licenses/LICENSE-2.0.html
licenseName=https://www.apache.org/licenses/LICENSE-2.0.html
licenseIconURL=null
citeAs=Ernesto Jimenez Ruiz, Ernesto Jimenez Ruiz. Pizza-Restaurants ontology. Revision: Version 02/03/2024. Retrieved from: https://w3id.org/city-kgs/restaurants/1.0.0
DOI=
status=Ontology Specification Draft
logo=
description=Ontology covering the domain of the Kaggle dataset Pizza Restaurants and the Pizza They Sell: https://www.kaggle.com/datafiniti/pizza-restaurants-and-the-pizza-they-sell
introduction=
backwardsCompatibleWith=
publisher=
publisherURI=
publisherInstitution=
publisherInstitutionURI=
authors=Ernesto Jimenez Ruiz;Ernesto Jimenez Ruiz
authorsURI=;
authorsInstitution=;
authorsInstitutionURI=;
contributors=
contributorsURI=
contributorsInstitution=
contributorsInstitutionURI=
importedOntologyNames=
importedOntologyURIs=
extendedOntologyNames=
extendedOntologyURIs=
RDFXMLSerialization=ontology.owl
TurtleSerialization=ontology.ttl
NTSerialization=ontology.nt
JSONLDSerialization=ontology.jsonld
images=
source=
seeAlso=
fundingGrants=
funders=
